  GV_GRAPH_KEY = 'subgraph cluster_01 {\nnodesep=0.05;color=white;\n'
    + 'key [label=<<table border="0" cellpadding="2" cellspacing="0" cellborder="0">'
    + '<tr><td align="right" port="pi">prototypal inheritance</td></tr>'
    + '<tr><td align="right" port="par">$parent</td></tr>'
    + '<tr><td align="right" port="sib">$$nextSibling</td></tr>'
    + '</table>>]\n'
    + 'key2 [label=<<table border="0" cellpadding="2" cellspacing="0" cellborder="0">'
    + '<tr><td port="pi">&nbsp;</td></tr>'
    + '<tr><td port="par">&nbsp;</td></tr>'
    + '<tr><td port="sib">&nbsp;</td></tr>'
    + '</table>>]\n'
    + 'key3 [label=<<table border="0" cellpadding="2" cellspacing="0" cellborder="0">'
    + '<tr><td align="right" port="refp">primitive reference</td></tr>'
    + '<tr><td align="right" port="refa">array reference</td></tr>'
    + '<tr><td align="right" port="refo">object reference</td></tr>'
    + '<tr><td align="right" port="refs">service reference</td></tr>'
    + '</table>>]\n'
    + 'key4 [label=<<table border="0" cellpadding="2" cellspacing="0" cellborder="0">'
    + '<tr><td port="refp">&nbsp;</td></tr>'
    + '<tr><td port="refa">&nbsp;</td></tr>'
    + '<tr><td port="refo">&nbsp;</td></tr>'
    + '<tr><td port="refs">&nbsp;</td></tr>'
    + '</table>>]'
    + 'key:pi:e  -> key2:pi:w  [style=' + PROTO_LINE_STYLE   + ']\n'
    + 'key:par:e -> key2:par:w [color=' + PARENT_LINE_COLOR  + ']\n'
    + 'key:sib:e -> key2:sib:w [color=' + SIBLING_LINE_COLOR + ']\n'
    + 'key3:refp:e -> key4:refp:w [color="' + REF_LINE_COLORS[PRIMITIVE_BGCOLOR]
      + '", style=' + REF_LINE_STYLE + ']\n'
    + 'key3:refa:e -> key4:refa:w [color="' + REF_LINE_COLORS[ARRAY_BGCOLOR]
      + '", style=' + REF_LINE_STYLE + ']\n'
    + 'key3:refo:e -> key4:refo:w [color="' + REF_LINE_COLORS[OBJECT_BGCOLOR]
      + '", style=' + REF_LINE_STYLE + ']\n'
    + 'key3:refs:e -> key4:refs:w [color="' + REF_LINE_COLORS[SERVICE_BGCOLOR]
      + '", style=' + REF_LINE_STYLE + ']\n'
    + 'key2:pi:e -> key3:refp:w [style=invis]'
    + '}',